# Generated by Django 4.2.6 on 2023-10-20 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_alter_people_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="people",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name_plural": "people",
            },
        ),
    ]
